INSERT INTO blogful_articles (title, content, date_published)
VALUES
    ('The Iconic Eames House Explained', 
    'Designed in 1949, The Eames House (Case Study House #8) became one of the most iconic architectural feats for Charles and Ray Eames. Though it feels industrial — it''s made primarily out of glass and steel — the house was meant to become one with nature.',
    '2018-08-01 12:00:00'),
    ('Who is Charlotte Perriand?', 
    'Born in 1903, Charlotte Perriand made an impact in the design world at the young age of 24. She caught the attention of Le Corbusier, and then joined his studio, where she created iconic furniture pieces with him and Pierre Jeanneret. She is known for creating a modular kitchen design in the 1940''s',
    '2018-09-01 12:00:00'),
    ('A Deeper Look at Case Study House #22', 
    'Pierre Koening designed Case Study House #22, also known as the Stahl House, in Los Angeles. The home was built in 1960 and is one of the best-known houses of mid-century Los Angeles.',
    '2018-10-01 12:00:00'),
    ('3 Fun Facts About the Farnsworth House', 
    '1. The Farnsworth House was designed by Mies van der Rohe for Dr. Edith Farnsworth between 1949-1951. 2. The home is raised above grade by over 5 feet to avoid flood damage. 3. The home is composed of three strong, horizontal steel forms – the terrace, the floor of the house, and the roof – attached to attenuated, steel flange columns.',
    '2018-11-01 12:00:00'),
    ('A House Designed by Eileen Gray', 
    'During the course of her career, Eileen Gray became known for her furniture design, but the self-taught architect wanted to be known for more than that. At 48 years old, she began work on her first architectural project: the E-1027 House (or Villa E-1027). She completed the house in 1929, at 51 years old.',
    '2018-12-01 12:00:00'),
    ('This John Lautner Home Looks Like a U.F.O.', 
    'Not every architect can claim that they created a structure most people liken to a U.F.O. But John Lautner, born in 1911, takes the cake for this with his 1960 Malin Residence (aka Chemosphere) in the Hollywood Hills. The octagon-shaped house sits 29 feet above the ground and seems to float amidst the nature surrounding it.',
    '2019-01-01 12:00:00'),
    ('Neutra''s Kaufmann House is a Dream', 
    'Built in 1946, the boxy 2-story Kaufmann House has many defining elements of modern architecture – a flat roof, pale exterior and shaded outdoor spaces – tailored to the arid climate of the Palm Springs desert. In 1996, the house was designated a historic site by the Palm Springs Historic Site Preservation Board.',
    '2019-02-01 12:00:00'),
    ('This Danish Architect Originally Pursued Painting', 
    'Danish architect Arne Jacobsen originally wanted to pursue painting as a career but found a love for furniture design and architecture instead. Born in 1902 in Copenhagen, Jacobsen was influenced by the work of Mies van der Rohe and Walter Gropius.',
    '2019-03-01 12:00:00'),
    ('Who is Lina Bo Bardi?',
    'Italian-Brazilian architect Lina Bo Bardi took on the big task of bringing to life the building that would house the São Paulo Museum of Art (MASP) in the 1940s. It was the first modern museum in the country, according to the museum''s website.',
    '2019-04-01 12:00:00'),
    ('The TWA Flight Center at JFK',
    'Eero Saarinen designed the Trans World Airline Flight Center in New York City''s JFK Airport. The structure opened in 1962 but in the early 2000s, it didn''t meet modern guidelines for security, so traffic was redirected to Terminal 5. It remained shuttered for more than a decade, until developer Tyler Morse decided to give it new life. In May 2019, it reopened as the TWA Hotel.',
    '2019-05-01 12:00:00'),
    ('Marmol Radziner is the Best Modern, Residential Architecture Firm',
    'Marmol Radziner is a design-build practice based in Los Angeles that was founded in 1989 by American architects Leo Marmol and Ron Radziner. The firm was awarded the AIA National Honor Award in 2000, recognizing their restoration of the Kaufmann Desert House in Palm Springs, California.',
    '2019-06-01 12:00:00'),
    ('Who is Walter Gropius?',
    'Known as the founder of the Bauhaus school, Walter Gropius was born in Berlin in 1833. He studied with architect Peter Behrens before starting his own practice with Adolf Meyer in 1910. In 1919, he officially founded the Bauhaus in Weimar, Germany.',
    '2019-07-01 12:00:00'),
    ('Schindler and Space Architecture',
    'In 1921, Rudolph Schindler decided to make roots in Los Angeles, where he built his own house. According to the MAK Center, Schindler focused primarily on the idea of "Space architecture," which meant paying close attention to a space''s interior.',
    '2019-08-01 12:00:00'),
    ('Who is Oscar Niemeyer?',
    'Born in 1907 in Rio de Janeiro, Oscar Niemeyer would come to influence architecture in his hometown and beyond. His projects included collaborations with figures like Le Corbusier, with whom he designed the United Nation Headquarters in New York.',
    '2019-09-01 12:00:00'),
    ('Marmol Radziner''s Canyon Collection Furniture',
    'The Marmol Radziner Canyon Collection for McGuire is inspired by the lush, verdant canyons of Los Angeles – welcome pockets of sun dappled greenery and rugged terrain in the vast expanse of the city.',
    '2019-10-01 12:00:00'),
    ('About the Architect of the Burbank Warner Bros. Record Headquarters',
    'Archibald Quincy Jones made his mark on Los Angeles in the 1950s and 1960s as an architect, educator, and critic. Born in Kansas City in 1913, he studied architecture at the University of Washington. Among his many projects — from houses to libraries — Jones also designed the 1975 Burbank Warner Bros. Records headquarters.',
    '2019-11-01 12:00:00'),
    ('How the Eames Foundation Began',
    'After Charles died in 1978, Ray explored various methods of preserving the Eames House, including the possibility of gifting the House to different institutions. None would guarantee that they would not de-access the house after ten years. Ray ultimately chose to give the house to Lucia Eames, her step-daughter, in order that she could continue to develop a plan for the preservation of the Eames House.',
    '2019-12-01 12:00:00'),
    ('Two Houses Designed by Pierre Koenig That Aren''t the Stahl House',
    'Koenig House #2 is the second Mid-Century Modern home Koenig designed for himself and his wife Gloria, reflecting his personal philosophy that industrial methods and materials could be used to produce inexpensive, distinctive, and environmentally friendly homes. The Bailey House was built for a couple open to the idea of a steel-framed house, which allowed architect Pierre Koenig to realize his vision of an open plan design that was both affordable and beautiful.',
    '2020-01-01 12:00:00'),
    ('Jewelry by Marmol Radziner',
    'Robin Cottle is married to Ron Radziner, who founded the multidisciplinary architecture, design and building practice Marmol Radziner with Leo Marmol in 1989. Cottle designs modest-yet-edgy pieces.',
    '2020-02-01 12:00:00'),
    ('The Theme Building at LAX',
    'The Theme Building is an iconic Space Age structure at the Los Angeles International Airport. Influenced by "Populuxe" architecture, it is an example of the Mid-century modern design movement later to become known as "Googie".',
    '2020-03-01 12:00:00');